  # psvita:
  # name: PS Vita
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout sources
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #         submodules: recursive
  #     - name: Setup PS Vita SDK
  #       run: scripts/psvita_sdk.sh
  windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      matrix:
        arch: ['x86', 'amd64']
      fail-fast: false
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Setup Visual Studio
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: Configure project
        run: cmake --preset "win32-ci-${{ matrix.arch }}"
      - name: Run appversion.sh
        run: regamedll/version/appversion.sh "${{ github.workspace }}/3rdparty/ReGameDLL_CS"
        shell: bash
        working-directory: 3rdparty/ReGameDLL_CS
      - name: Build
        run: cmake --build .
        working-directory: build
      - name: Package
        run: cpack --config CPackConfig.cmake
        working-directory: build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ matrix.arch }}
          path: build/*.zip
  
